name: Build

on:
  push:
    branches: [main]

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin,aarch64-apple-darwin
      - run: cargo install tauri-cli --version "^1.6" --locked
      - run: cargo tauri build --bundles app --target universal-apple-darwin
      - uses: actions/upload-artifact@v4
        with:
          name: ScreenTracker-Mac
          path: src-tauri/target/universal-apple-darwin/release/bundle/macos/*.app

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo install tauri-cli --version "^1.6" --locked
      - run: cargo tauri build
        working-directory: .
      - uses: actions/upload-artifact@v4
        with:
          name: ScreenTracker-Windows
          path: src-tauri/target/release/bundle/msi/*.msi
